name: annadhatha_connect
description: "Farmer ↔ Retailer Direct Trade Platform"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI & Navigation
  cupertino_icons: ^1.0.8
  go_router: ^14.2.7
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0

  # State Management
  flutter_riverpod: ^2.5.1

  # Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5

  # HTTP & API
  http: ^1.2.2
  json_annotation: ^4.9.0

  # Local Storage
  shared_preferences: ^2.3.2

  # Image & File Handling
  image_picker: ^1.1.2
  path_provider: ^2.1.4

  # Voice & Speech
  speech_to_text: ^6.6.0
  permission_handler: ^11.3.1

  # Payment
  razorpay_flutter: ^1.3.3

  # Utils
  intl: ^0.20.2
  uuid: ^4.5.1
  url_launcher: ^6.3.1
  package_info_plus: ^8.0.2
  device_info_plus: ^10.1.2
  connectivity_plus: ^6.0.5

  # UI Components
  flutter_staggered_grid_view: ^0.7.0
  pull_to_refresh: ^2.0.0
  flutter_slidable: ^3.1.1
  pin_code_fields: ^8.0.1
  country_picker: ^2.0.24

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Code Generation
  build_runner: ^2.4.13
  json_serializable: ^6.8.0

  # Testing
  mockito: ^5.4.4
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/translations/

  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700